name: Python package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        python-version: [2.7, 3.5]
        exclude:
          # This combination requires MSVC 9, which is difficult here
          - os: windows-latest
            python-version: 2.7
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build and install package
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python setup.py bdist_wheel
        pip install --find-links=dist --no-index distorm3
    - uses: actions/upload-artifact@v1
      with:
        name: Wheels
        path: dist
    - name: Test importing
      run: python -c 'import distorm3'
    - name: Install yasm (macOS)
      run: brew install yasm
      if: runner.os == 'macOS'
    - name: Install yasm (Ubuntu)
      run: sudo apt-get install -y yasm
      if: runner.os == 'Linux'
    - name: Copy yasm (Windows)
      run: copy test-deps\yasm-1.3.0-win64.exe python\yasm.exe
      if: runner.os == 'Windows'
    - name: Run test_distorm3.py
      working-directory: ./python
      run: python test_distorm3.py
